#pragma once

enum EAppOwnershipFlags
{
	EAPPOWNERSHIPFLAGS_NONE = 0,
	EAPPOWNERSHIPFLAGS_SUBSCRIBED = 0x1,
	EAPPOWNERSHIPFLAGS_FREE = 0x2,
	EAPPOWNERSHIPFLAGS_REGION_RESTRICTED = 0x4,
	EAPPOWNERSHIPFLAGS_LOW_VIOLENCE = 0x8,
	EAPPOWNERSHIPFLAGS_INVALID_PLATFORM = 0x10,
	EAPPOWNERSHIPFLAGS_BORROWED = 0x20,
	EAPPOWNERSHIPFLAGS_FREE_WEEKEND = 0x40,
	EAPPOWNERSHIPFLAGS_RETAIL = 0x80,
	EAPPOWNERSHIPFLAGS_LOCKED = 0x100,
	EAPPOWNERSHIPFLAGS_PENDING = 0x200,
	EAPPOWNERSHIPFLAGS_EXPIRED = 0x400,
	EAPPOWNERSHIPFLAGS_PERMANENT = 0x800,
	EAPPOWNERSHIPFLAGS_RECURRING = 0x1000,
	EAPPOWNERSHIPFLAGS_CANCELED = 0x2000,
	EAPPOWNERSHIPFLAGS_AUTO_GRANT = 0x4000,
	EAPPOWNERSHIPFLAGS_PENDING_GIFT = 0x8000,
	EAPPOWNERSHIPFLAGS_UNKNOWN = 0x10000,
	EAPPOWNERSHIPFLAGS_UNKNOWN2 = 0x20000,
	EAPPOWNERSHIPFLAGS_SITE_LICENSE = 0x40000,
	EAPPOWNERSHIPFLAGS_LEGACY_FREE_SUB = 0x80000,
	EAPPOWNERSHIPFLAGS_INVALID_OS_TYPE = 0x100000,
};
