#pragma once

enum ELicenseType
{
	ELICENSE_TYPE_NONE = 0x0,
	ELICENSE_TYPE_SINGLE_PURCHASE = 0x1,
	ELICENSE_TYPE_SINGLE_PURCHASE_LIMITED_USE = 0x2,
	ELICENSE_TYPE_RECURRING_CHARGE = 0x3,
	ELICENSE_TYPE_UNKNOWN = 0x4,
	ELICENSE_TYPE_UNKNOWN2 = 0x5,
	ELICENSE_TYPE_RECURRING_PAYMENT_OPTION = 0x6,
	ELICENSE_TYPE_LIMITED_USE,_DELAYED_ACTIVATION = 0x7,
};
