#pragma once

enum ELicenseFlags
{
	ELICENSE_FLAGS_NONE = 0x0,
	ELICENSE_FLAGS_RENEW_NEXT_PERIOD = 0x1,
	ELICENSE_FLAGS_RENEW_FAILED = 0x2,
	ELICENSE_FLAGS_PENDING = 0x4,
	ELICENSE_FLAGS_EXPIRED = 0x8,
	ELICENSE_FLAGS_CANCELLED_BY_USER = 0x10,
	ELICENSE_FLAGS_CANCELLED_BY_ADMIN = 0x20,
	ELICENSE_FLAGS_LOW_VIOLENCE = 0x40,
	ELICENSE_FLAGS_LICENSE_IMPORTED_FROM_STEAM2 = 0x80,
	ELICENSE_FLAGS_FORCE_RUN_RESTRICTION = 0x100,
	ELICENSE_FLAGS_REGION_RESTRICTION_EXPIRED = 0x200,
	ELICENSE_FLAGS_CANCELLED_BY_FRIENDLY_FRAUD_LOCK = 0x400,
	ELICENSE_FLAGS_NOT_ACTIVATED = 0x800,
	//ELICENSE_FLAGS_UNKNOWN = 0x1000,
	ELICENSE_FLAGS_PENDING_REFUND = 0x2000,
	ELICENSE_FLAGS_BORROWED = 0x4000,
	ELICENSE_FLAGS_RELEASE_STATE_OVERRIDE = 0x8000,
	//ELICENSE_FLAGS_UNKNOWN = 0x10000,
	//ELICENSE_FLAGS_UNKNOWN = 0x20000,
	ELICENSE_FLAGS_CANCELLED_BY_PARTNER = 0x40000,
	ELICENSE_FLAGS_NON_PERMANENT = 0x80000,
	ELICENSE_FLAGS_PREFERRED_OWNER = 0x100000,
};
